name: Build Solution
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution (x64 Release)
        run: msbuild idd/LGIdd.sln /p:Configuration=Release /p:Platform=x64
        env:
          Git: git

      - name: Collect build outputs
        run: |
          mkdir artifacts
          copy **\x64\Release\*.exe artifacts\
          copy **\x64\Release\*.dll artifacts\ || echo "No DLLs found"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: artifacts
